fail_fast: true
repos:
- repo: local
  hooks:
  - id: system
    name: Requirements
    entry: poetry run poetry
    pass_filenames: false
    language: system
    stages: [ manual ]
    args:
      [
        "export",
        "--format=requirements.txt",
        "--without-hashes",
        "--dev",
        "--output=docs/requirements.txt",
      ]

  - id: black
    name: black
    stages: [commit]
    language: system
    entry: poetry run black .
    types: [python]

  - id: flake8
    name: flake8
    stages: [commit]
    language: system
    entry: poetry run flake8
    types: [python]
    exclude: setup.py

  - id: isort
    name: isort
    stages: [commit]
    language: system
    entry: poetry run isort .
    types: [python]

# I don't understand mypy, so I am disabling this for now
#  - id: mypy
#    name: mypy
#    stages: [commit]
#    language: system
#    entry: poetry run mypy
#    types: [python]
#    require_serial: true

  - id: pylint
    name: pylint
    stages: [commit]
    language: system
    entry: poetry run pylint
    types: [python]
    args:
      [
        "--disable=line-too-long",
        "--fail-under=7.0",
        "--jobs=0",
        "--reports=n",
        "--score=y",
        "pybase",
        "test",
      ]

# I am a bad developer who writes no tests, so disabled for now
#  - id: pytest
#    name: pytest
#    stages: [commit]
#    language: system
#    entry: poetry run pytest
#    types: [python]
#    pass_filenames: false
#
#  - id: pytest-cov
#    name: pytest
#    stages: [push]
#    language: system
#    entry: poetry run pytest --cov --cov-fail-under=100
#    types: [python]
#    pass_filenames: false
